---
bind_allow_query: ["any"]
bind_allow_recursion: ["any"]
bind_recursion: true
bind_forwarders:
  - 1.1.1.1 
bind_forward_only: false
bind_dnssec_enable: false
bind_dnssec_validation: false
bind_query_log: "data/query.log"
bind_listen_ipv4: ["any"]
rhbase_firewall_allow_ports:
  - 53/udp
  - 53/tcp
  - 9100/tcp
bind_zones:
  - name: exam.lan
    primaries: 
      - 172.16.128.1
    hosts:
      - name: r001
        ip: 172.16.255.254
      - name: srv001
        ip: 172.16.128.1
        aliases:
          - ns
          - ns1
          - dhcp 
      - name: srv002
        ip: 172.16.128.2
      - name: "@"
        ip: 172.16.128.100
        aliases:
          - www

dhcp_global_classes:
  - name: vbox
    match: 'match if binary-to-ascii(16,8,":",substring(hardware, 1, 3)) = "8:0:27"'

dhcp_global_server_state: started

dhcp_subnets:
  - ip: 172.16.0.0
    netmask: 255.255.0.0
    range_begin: 172.16.0.2
    range_end: 172.16.127.254
    domain_name_servers:
      - 172.16.128.1
    max_lease_time: 14400  # 4 hours
    routers: 172.16.255.254
