promtail_version: "latest"
promtail_http_listen_port: 9080
promtail_http_listen_address: "0.0.0.0"
promtail_expose_port: false
promtail_positions_path: "/var/lib/promtail"
promtail_user_append_groups:
  - "systemd-journal"
promtail_download_url_rpm: "https://github.com/grafana/loki/releases/download/v{{ promtail_version }}/promtail-{{ promtail_version }}.{{ __promtail_arch }}.rpm"
promtail_download_url_deb: "https://github.com/grafana/loki/releases/download/v{{ promtail_version }}/promtail_{{ promtail_version }}_{{ __promtail_arch }}.deb"
promtail_server:
  http_listen_port: "{{ promtail_http_listen_port }}"
  http_listen_address: "{{ promtail_http_listen_address }}"
promtail_positions:
  filename: "{{ promtail_positions_path }}/positions.yaml"
promtail_clients:
  - url: http://localhost:3100/loki/api/v1/push 